version: '3'
services:
  app:
    build: .
    volumes:
      - /code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
