# Generated by Django 4.2.7 on 2023-11-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_books', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
